---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-sshfs
  selector:
    matchLabels:
      csi.sshfs.io/remote: backup
