apiVersion: v1
kind: Secret
metadata:
  name: demo-ssh-identity
  namespace: default
  labels:
    csi.sshfs.io/remote: backup
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b...==
    -----END OPENSSH PRIVATE KEY-----
