kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include ( printf "%s.%s" .Chart.Name "fullname" ) . }}-controller:binder
  labels:
    {{- include ( printf "%s.%s" .Chart.Name "labels" ) . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include ( printf "%s.%s" .Chart.Name "fullname" ) . }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include ( printf "%s.%s" .Chart.Name "fullname" ) . }}-controller:binder
  apiGroup: rbac.authorization.k8s.io
