{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ( printf "%s.%s" .Chart.Name "serviceAccountName" ) . }}-controller
  labels:
    {{- include ( printf "%s.%s" .Chart.Name "labels" ) . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
