apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include ( printf "%s.%s" .Chart.Name "fullname" ) . }}
  labels:
    {{- include ( printf "%s.%s" .Chart.Name "labels" ) . | nindent 4 }}
    app.kubernetes.io/instance: controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include ( printf "%s.%s" .Chart.Name "selectorLabels" ) . | nindent 6 }}
      app.kubernetes.io/instance: controller
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ( printf "%s.%s" .Chart.Name "labels" ) . | nindent 8 }}
        app.kubernetes.io/instance: controller
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include ( printf "%s.%s" .Chart.Name "serviceAccountName" ) . }}-controller
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--csi-driver-name={{ .Values.csi.driver.name }}"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
        - name: csi-attacher
          image: {{ .Values.csi.attacher.registry }}{{ .Values.csi.attacher.repository }}:{{ .Values.csi.attacher.tag }}
          imagePullPolicy: {{ .Values.csi.attacher.pullPolicy }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
