apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include ( printf "%s.%s" .Chart.Name "fullname" ) . }}
  labels:
    {{- include ( printf "%s.%s" .Chart.Name "labels" ) . | nindent 4 }}
provisioner: {{ .Values.csi.driver.name }}
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
